#!/usr/bin/env tsx
/**
 * Fetch popular Google Fonts and regenerate the catalog file.
 *
 * Usage:
 *   GOOGLE_FONTS_API_KEY=your-key pnpm --filter @payloadtwist/web fetch-google-fonts
 *
 * Requires a Google Fonts API key. Get one at:
 *   https://developers.google.com/fonts/docs/developer_api#identifying_your_application_to_google
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const VALID_CATEGORIES = new Set([
  'sans-serif',
  'serif',
  'display',
  'handwriting',
  'monospace',
])

const OUTPUT_PATH = path.resolve(
  __dirname,
  '../src/payload-theme/google-fonts-catalog.ts',
)

interface GoogleFontsApiItem {
  family: string
  category: string
}

interface GoogleFontsApiResponse {
  items: GoogleFontsApiItem[]
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const apiKey = process.env.GOOGLE_FONTS_API_KEY
  if (!apiKey) {
    console.error(
      'Error: GOOGLE_FONTS_API_KEY environment variable is required.\n\n' +
        'Get a key at: https://developers.google.com/fonts/docs/developer_api#identifying_your_application_to_google\n\n' +
        'Usage:\n' +
        '  GOOGLE_FONTS_API_KEY=your-key pnpm --filter @payloadtwist/web fetch-google-fonts',
    )
    process.exit(1)
  }

  const url = `https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity&key=${apiKey}`

  console.log('Fetching Google Fonts catalog...')
  const response = await fetch(url)

  if (!response.ok) {
    console.error(
      `Google Fonts API error: ${response.status} ${response.statusText}`,
    )
    const body = await response.text()
    console.error(body)
    process.exit(1)
  }

  const data = (await response.json()) as GoogleFontsApiResponse
  const fonts = data.items
    .filter((item) => VALID_CATEGORIES.has(item.category))
    .map((item) => ({
      family: item.family,
      category: item.category,
    }))

  console.log(
    `Fetched ${data.items.length} total fonts, ${fonts.length} in valid categories.`,
  )

  // Group by category and pick top N from each
  const limits: Record<string, number> = {
    'sans-serif': 50,
    serif: 20,
    display: 15,
    handwriting: 10,
    monospace: 13,
  }

  const grouped: Record<string, { family: string; category: string }[]> = {}
  for (const font of fonts) {
    const cat = font.category
    if (!grouped[cat]) grouped[cat] = []
    if (grouped[cat].length < (limits[cat] ?? 10)) {
      grouped[cat].push(font)
    }
  }

  // Flatten in category order
  const categoryOrder = [
    'sans-serif',
    'serif',
    'display',
    'handwriting',
    'monospace',
  ]
  const selected: { family: string; category: string }[] = []
  for (const cat of categoryOrder) {
    if (grouped[cat]) {
      selected.push(...grouped[cat])
    }
  }

  // Build the category comment labels
  const categoryLabels: Record<string, string> = {
    'sans-serif': 'Sans-serif',
    serif: 'Serif',
    display: 'Display',
    handwriting: 'Handwriting',
    monospace: 'Monospace',
  }

  // Generate the font entries as TypeScript
  let catalogEntries = ''
  let currentCategory = ''
  for (const font of selected) {
    if (font.category !== currentCategory) {
      const count = grouped[font.category]?.length ?? 0
      const label = categoryLabels[font.category] ?? font.category
      if (currentCategory !== '') catalogEntries += '\n'
      catalogEntries += `  // ${label} (~${count})\n`
      currentCategory = font.category
    }
    catalogEntries += `  { family: '${font.family.replace(/'/g, "\\'")}', category: '${font.category}' },\n`
  }

  const fileContent = `/**
 * Google Fonts catalog for the PayloadTwist font picker.
 *
 * This file is auto-generated by \`pnpm --filter @payloadtwist/web fetch-google-fonts\`.
 * Manual edits to GOOGLE_FONTS_CATALOG will be overwritten.
 * SYSTEM_FONTS and type definitions are preserved across regeneration.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export type FontCategory = 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'

export interface GoogleFont {
  family: string
  category: FontCategory
}

// ─── System Fonts ───────────────────────────────────────────────────────────

export const SYSTEM_FONTS = [
  { label: 'System Default', value: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: "'Times New Roman', Times, serif" },
  { label: 'Courier New', value: "'Courier New', Courier, monospace" },
  { label: 'Arial', value: 'Arial, Helvetica, sans-serif' },
  { label: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
] as const

// ─── Google Fonts Catalog ───────────────────────────────────────────────────
// ~${selected.length} popular fonts sorted by popularity, across all categories.

export const GOOGLE_FONTS_CATALOG: GoogleFont[] = [
${catalogEntries}]
`

  fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf-8')
  console.log(`Wrote ${selected.length} fonts to ${OUTPUT_PATH}`)
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
