import { describe, it, expect } from 'vitest'
import { buildCSSString, generateMinimalPayloadCSS, generateExportCSS } from '@/payload-theme/generator'
import type { PayloadThemeConfig } from '@/payload-theme/types'

const emptyConfig: PayloadThemeConfig = {
  light: {},
  dark: {},
  componentOverrides: {},
  bemOverrides: {},
}

const sampleConfig: PayloadThemeConfig = {
  light: { '--color-base-0': '#f8f9fa' },
  dark: { '--theme-bg': '#0d0d0d' },
  componentOverrides: {},
  bemOverrides: {},
}

describe('buildCSSString', () => {
  it('returns empty string for empty config', () => {
    expect(buildCSSString(emptyConfig)).toBe('')
  })

  it('wraps light vars in :root block', () => {
    const css = buildCSSString(sampleConfig)
    expect(css).toContain(':root {')
    expect(css).toContain('--color-base-0: #f8f9fa;')
  })

  it('wraps dark vars in [data-theme="dark"] block', () => {
    const css = buildCSSString(sampleConfig)
    expect(css).toContain('[data-theme="dark"] {')
    expect(css).toContain('--theme-bg: #0d0d0d;')
  })
})

describe('generateMinimalPayloadCSS', () => {
  it('returns empty for config matching defaults', () => {
    const css = generateMinimalPayloadCSS(emptyConfig)
    expect(css).toBe('')
  })

  it('emits only changed vars', () => {
    const css = generateMinimalPayloadCSS(sampleConfig)
    if (css) {
      expect(css).toContain('#f8f9fa')
    }
  })
})

describe('generateExportCSS', () => {
  it('includes header comment', () => {
    const css = generateExportCSS(sampleConfig)
    expect(css).toContain('Generated by payloadtwist')
  })
})
