import { getDefaultTheme, getVariablesByCategory, PAYLOAD_VARIABLES } from './config.js'
import type { PayloadThemeConfig } from './types.ts'

// Theme vars that must have both light AND dark values emitted together.
// Our unlayered CSS beats Payload's @layer payload-default, so if we emit
// :root { --theme-text: #custom } without a matching [data-theme="dark"]
// rule, the light value bleeds into dark mode.
const LINKED_DARK_VARS = new Set([
  '--theme-text',
  '--theme-bg',
  '--theme-input-bg',
  '--theme-overlay',
])

// ─── Internal helpers ────────────────────────────────────────────────────────

function lightBlock(vars: Record<string, string>): string {
  const entries = Object.entries(vars)
    .filter(([, v]) => v !== '')
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')
  if (!entries) return ''
  return `:root {\n${entries}\n}`
}

function darkBlock(vars: Record<string, string>): string {
  const entries = Object.entries(vars)
    .filter(([, v]) => v !== '')
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')
  if (!entries) return ''
  return `[data-theme="dark"] {\n${entries}\n}`
}

// ─── Export header / footer ──────────────────────────────────────────────────

const EXPORT_HEADER = `/**
 * Custom Payload CMS Theme
 * Generated by payloadtwist
 *
 * Paste this into your project's custom.scss (or custom.css).
 * See: https://payloadcms.com/docs/admin/customizing-css
 *
 * Payload wraps all its CSS in @layer payload-default, so this
 * unlayered CSS automatically takes priority — no !important needed.
 */`

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Builds the live injection string (minimal, no comments).
 * Used for real-time iframe injection.
 */
export function buildCSSString(config: PayloadThemeConfig): string {
  const parts: string[] = []
  const light = lightBlock(config.light)
  if (light) parts.push(light)
  const dark = darkBlock(config.dark)
  if (dark) parts.push(dark)
  return parts.join('\n\n')
}

/**
 * Injects config vars into the Payload admin iframe's <head>.
 * Creates/updates a <style id="tweakpayload-vars"> tag.
 *
 * Only injects vars that differ from the extracted defaults.
 * Injecting all defaults (via buildCSSString) would override Payload's
 * compiled CSS with our schema-extracted values, which may not match
 * exactly — corrupting the admin appearance before the user changes anything.
 *
 * For same-origin iframes, uses direct DOM access.
 * For cross-origin iframes, uses postMessage (requires live-preview.js on the target).
 */
export function injectIntoIframe(config: PayloadThemeConfig): void {
  const iframe = document.querySelector('iframe#payload-preview') as HTMLIFrameElement | null
  if (!iframe) return

  const varsCSS = generateMinimalPayloadCSS(config)
  const bemCss = buildBemCSS(config.bemOverrides)
  const componentCSS = config.componentOverrides
    ? buildComponentOverrideCSS(config.componentOverrides)
    : ''

  // Try same-origin direct DOM access first
  try {
    const iframeDoc = iframe.contentDocument ?? iframe.contentWindow?.document
    if (iframeDoc) {
      let styleTag = iframeDoc.getElementById('tweakpayload-vars') as HTMLStyleElement | null
      if (!styleTag) {
        styleTag = iframeDoc.createElement('style')
        styleTag.id = 'tweakpayload-vars'
        iframeDoc.head.appendChild(styleTag)
      }
      styleTag.textContent = bemCss ? varsCSS + '\n\n' + bemCss : varsCSS

      let compTag = iframeDoc.getElementById('tweakpayload-components') as HTMLStyleElement | null
      if (!compTag) {
        compTag = iframeDoc.createElement('style')
        compTag.id = 'tweakpayload-components'
        iframeDoc.head.appendChild(compTag)
      }
      compTag.textContent = componentCSS
      return
    }
  } catch {
    // Cross-origin — fall through to postMessage
  }

  // Cross-origin: use postMessage (requires live-preview.js on the target)
  iframe.contentWindow?.postMessage(
    {
      type: 'payloadtwist:inject',
      payload: {
        varsCSS: bemCss ? varsCSS + '\n\n' + bemCss : varsCSS,
        componentCSS,
        bemCSS: '',
      },
    },
    '*',
  )
}

/**
 * Temporarily highlights a BEM block in the iframe with an outline.
 * Removes after 2 seconds. Works for both same-origin and cross-origin iframes.
 */
export function highlightBemBlock(blockName: string): void {
  const iframe = document.querySelector('iframe#payload-preview') as HTMLIFrameElement | null
  if (!iframe) return

  // Try same-origin direct DOM access first
  try {
    const iframeDoc = iframe.contentDocument ?? iframe.contentWindow?.document
    if (iframeDoc) {
      const styleId = 'tweakpayload-highlight'
      let styleTag = iframeDoc.getElementById(styleId) as HTMLStyleElement | null
      if (!styleTag) {
        styleTag = iframeDoc.createElement('style')
        styleTag.id = styleId
        iframeDoc.head.appendChild(styleTag)
      }
      styleTag.textContent = `.${blockName} { outline: 2px solid #3b82f6 !important; outline-offset: 2px; }`
      setTimeout(() => {
        if (styleTag) styleTag.textContent = ''
      }, 2000)
      return
    }
  } catch {
    // Cross-origin — fall through to postMessage
  }

  iframe.contentWindow?.postMessage(
    { type: 'payloadtwist:highlight', payload: { blockName } },
    '*',
  )
}

/**
 * Sets the iframe's data-theme attribute for light/dark mode.
 * Works for both same-origin and cross-origin iframes.
 */
export function setIframeTheme(theme: 'light' | 'dark'): void {
  const iframe = document.querySelector('iframe#payload-preview') as HTMLIFrameElement | null
  if (!iframe) return

  try {
    const iframeDoc = iframe.contentDocument ?? iframe.contentWindow?.document
    if (iframeDoc) {
      iframeDoc.documentElement.setAttribute('data-theme', theme)
      return
    }
  } catch {
    // Cross-origin — fall through to postMessage
  }

  iframe.contentWindow?.postMessage(
    { type: 'payloadtwist:theme', payload: { theme } },
    '*',
  )
}

// ─── Component override helpers ───────────────────────────────────────────────

/** Groups component overrides by selector. */
function groupOverridesBySelector(
  overrides: Record<string, string>,
): Map<string, Array<[string, string]>> {
  const bySelector = new Map<string, Array<[string, string]>>()
  for (const [key, value] of Object.entries(overrides)) {
    const sep = key.indexOf('||')
    if (sep === -1) continue
    const selector = key.slice(0, sep)
    const property = key.slice(sep + 2)
    if (!bySelector.has(selector)) bySelector.set(selector, [])
    bySelector.get(selector)!.push([property, value])
  }
  return bySelector
}

/**
 * Build component override CSS for live iframe injection.
 * Uses !important to beat Payload's compiled styles in the same document.
 */
export function buildComponentOverrideCSS(overrides: Record<string, string>): string {
  const bySelector = groupOverridesBySelector(overrides)
  if (bySelector.size === 0) return ''
  const parts: string[] = ['/* Component Visual Overrides */']
  for (const [selector, props] of bySelector) {
    const lines = props.map(([p, v]) => `  ${p}: ${v} !important;`).join('\n')
    parts.push(`${selector} {\n${lines}\n}`)
  }
  return parts.join('\n')
}

/**
 * Build component override CSS for export (custom.scss).
 * No !important — custom.scss is unlayered and already beats @layer payload-default.
 */
function buildComponentOverrideCSSForExport(overrides: Record<string, string>): string {
  const bySelector = groupOverridesBySelector(overrides)
  if (bySelector.size === 0) return ''
  const parts: string[] = ['/* Component Overrides */']
  for (const [selector, props] of bySelector) {
    const lines = props.map(([p, v]) => `  ${p}: ${v};`).join('\n')
    parts.push(`${selector} {\n${lines}\n}`)
  }
  return parts.join('\n\n')
}

// ─── BEM helpers ──────────────────────────────────────────────────────────────

export function buildBemCSS(bemOverrides?: Record<string, string>): string {
  if (!bemOverrides) return ''
  const parts: string[] = []
  for (const [, css] of Object.entries(bemOverrides)) {
    if (css.trim()) parts.push(css.trim())
  }
  return parts.length > 0 ? `/* BEM Component Overrides */\n${parts.join('\n\n')}` : ''
}

// ─── Category helpers ─────────────────────────────────────────────────────────

const CATEGORY_ORDER = [
  { key: 'base-scale', comment: '/* Base Color Scale (--color-base-*) */' },
  { key: 'theme', comment: '/* Theme Colors */' },
  { key: 'status.success', comment: '/* Success */' },
  { key: 'status.warning', comment: '/* Warning */' },
  { key: 'status.error', comment: '/* Error */' },
  { key: 'typography', comment: '/* Typography */' },
  { key: 'layout', comment: '/* Spacing & Layout */' },
] as const

const DARK_MODE_FOOTER = `/**
 * Dark mode notes:
 * - Elevation vars (--theme-elevation-*) are auto-inverted by Payload — do not override them.
 * - Status colors (--color-success/warning/error-*) are also auto-inverted.
 * - Only --theme-bg, --theme-text, --theme-input-bg, --theme-overlay need
 *   explicit [data-theme="dark"] overrides.
 */`

function buildCategoryLightLines(categoryKey: string, vars: Record<string, string>): string[] {
  return getVariablesByCategory(categoryKey)
    .filter((v) => v.overridable && vars[v.var] !== undefined && vars[v.var] !== '')
    .map((v) => `  ${v.var}: ${vars[v.var]};`)
}

/**
 * Human-readable CSS output with category comments.
 * Includes all overridable vars, for "Copy CSS".
 */
export function generatePayloadCSS(config: PayloadThemeConfig): string {
  const lightLines: string[] = []
  const darkLines: string[] = []

  for (const { key, comment } of CATEGORY_ORDER) {
    const catLightLines = buildCategoryLightLines(key, config.light)
    if (catLightLines.length > 0) {
      lightLines.push(`  ${comment}`)
      lightLines.push(...catLightLines)
      lightLines.push('')
    }
  }

  // Dark block: only explicit darkMode vars
  for (const [varName, value] of Object.entries(config.dark)) {
    if (value !== '') {
      const v = PAYLOAD_VARIABLES[varName]
      if (v?.darkMode === 'explicit') {
        darkLines.push(`  ${varName}: ${value};`)
      }
    }
  }

  const parts: string[] = [EXPORT_HEADER]

  if (lightLines.length > 0) {
    // Trim trailing empty line
    const trimmed = lightLines[lightLines.length - 1] === '' ? lightLines.slice(0, -1) : lightLines
    parts.push(`:root {\n${trimmed.join('\n')}\n}`)
  }

  if (darkLines.length > 0) {
    parts.push(`[data-theme="dark"] {\n${darkLines.join('\n')}\n}`)
  }

  if (darkLines.length > 0 || lightLines.some((l) => l.includes('--color-base-'))) {
    parts.push(DARK_MODE_FOOTER)
  }

  const compCss = config.componentOverrides
    ? buildComponentOverrideCSSForExport(config.componentOverrides)
    : ''
  if (compCss) parts.push(compCss)

  const bemCss = buildBemCSS(config.bemOverrides)
  if (bemCss) parts.push(bemCss)

  return parts.join('\n\n')
}

/**
 * Minimal CSS output — only vars that differ from the default theme.
 * Used for live iframe injection (no header/footer, uses !important for components).
 */
export function generateMinimalPayloadCSS(config: PayloadThemeConfig): string {
  const defaults = getDefaultTheme()
  const changedLight: Record<string, string> = {}
  const changedDark: Record<string, string> = {}

  for (const [k, v] of Object.entries(config.light)) {
    if (v !== (defaults.light[k] ?? '')) {
      changedLight[k] = v
    }
  }
  for (const [k, v] of Object.entries(config.dark)) {
    if (v !== (defaults.dark[k] ?? '')) {
      changedDark[k] = v
    }
  }

  // Ensure linked theme vars always emit both light + dark values together.
  for (const varName of LINKED_DARK_VARS) {
    if (changedLight[varName] && !changedDark[varName] && config.dark[varName]) {
      changedDark[varName] = config.dark[varName]
    }
    if (changedDark[varName] && !changedLight[varName] && config.light[varName]) {
      changedLight[varName] = config.light[varName]
    }
  }

  const parts: string[] = []
  const light = lightBlock(changedLight)
  if (light) parts.push(light)
  const dark = darkBlock(changedDark)
  if (dark) parts.push(dark)

  const bemCss = buildBemCSS(config.bemOverrides)
  if (bemCss) parts.push(bemCss)

  const compCss = config.componentOverrides
    ? buildComponentOverrideCSS(config.componentOverrides)
    : ''
  if (compCss) parts.push(compCss)

  return parts.join('\n\n')
}

/**
 * Minimal export CSS — only vars that differ from defaults.
 * Includes header comment, no !important on component overrides.
 * This is what users copy into their custom.scss.
 */
export function generateExportCSS(config: PayloadThemeConfig): string {
  const defaults = getDefaultTheme()
  const changedLight: Record<string, string> = {}
  const changedDark: Record<string, string> = {}

  for (const [k, v] of Object.entries(config.light)) {
    if (v !== (defaults.light[k] ?? '')) {
      changedLight[k] = v
    }
  }
  for (const [k, v] of Object.entries(config.dark)) {
    if (v !== (defaults.dark[k] ?? '')) {
      changedDark[k] = v
    }
  }

  // Ensure linked theme vars always emit both light + dark values together.
  for (const varName of LINKED_DARK_VARS) {
    if (changedLight[varName] && !changedDark[varName] && config.dark[varName]) {
      changedDark[varName] = config.dark[varName]
    }
    if (changedDark[varName] && !changedLight[varName] && config.light[varName]) {
      changedLight[varName] = config.light[varName]
    }
  }

  const hasBaseScale = Object.keys(changedLight).some((k) => k.startsWith('--color-base-'))
  const hasDarkChanges = Object.keys(changedDark).length > 0

  const parts: string[] = [EXPORT_HEADER]

  // Build categorized light block instead of flat dump
  const lightLines: string[] = []
  for (const { key, comment } of CATEGORY_ORDER) {
    const catLines = buildCategoryLightLines(key, changedLight)
    if (catLines.length > 0) {
      lightLines.push(`  ${comment}`)
      lightLines.push(...catLines)
      lightLines.push('')
    }
  }
  // Also include any changed vars not covered by CATEGORY_ORDER
  const categorizedVars = new Set(
    CATEGORY_ORDER.flatMap(({ key }) =>
      getVariablesByCategory(key).map((v) => v.var),
    ),
  )
  const uncategorized = Object.entries(changedLight).filter(
    ([k, v]) => v !== '' && !categorizedVars.has(k),
  )
  if (uncategorized.length > 0) {
    lightLines.push('  /* Other */')
    lightLines.push(...uncategorized.map(([k, v]) => `  ${k}: ${v};`))
    lightLines.push('')
  }

  if (lightLines.length > 0) {
    const trimmed = lightLines[lightLines.length - 1] === '' ? lightLines.slice(0, -1) : lightLines
    parts.push(`:root {\n${trimmed.join('\n')}\n}`)
  }

  if (hasDarkChanges) {
    const dark = darkBlock(changedDark)
    if (dark) parts.push(dark)
  }

  if (hasDarkChanges || hasBaseScale) {
    parts.push(DARK_MODE_FOOTER)
  }

  const compCss = config.componentOverrides
    ? buildComponentOverrideCSSForExport(config.componentOverrides)
    : ''
  if (compCss) parts.push(compCss)

  const bemCss = buildBemCSS(config.bemOverrides)
  if (bemCss) parts.push(bemCss)

  return parts.join('\n\n')
}
