/**
 * Google Fonts catalog for the PayloadTwist font picker.
 *
 * This file is auto-generated by `pnpm --filter @payloadtwist/web fetch-google-fonts`.
 * Manual edits to GOOGLE_FONTS_CATALOG will be overwritten.
 * SYSTEM_FONTS and type definitions are preserved across regeneration.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export type FontCategory = 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'

export interface GoogleFont {
  family: string
  category: FontCategory
}

// ─── System Fonts ───────────────────────────────────────────────────────────

export const SYSTEM_FONTS = [
  { label: 'System Default', value: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: "'Times New Roman', Times, serif" },
  { label: 'Courier New', value: "'Courier New', Courier, monospace" },
  { label: 'Arial', value: 'Arial, Helvetica, sans-serif' },
  { label: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
] as const

// ─── Google Fonts Catalog ───────────────────────────────────────────────────
// ~110 popular fonts sorted by popularity, across all categories.

export const GOOGLE_FONTS_CATALOG: GoogleFont[] = [
  // Sans-serif (~50)
  { family: 'Roboto', category: 'sans-serif' },
  { family: 'Open Sans', category: 'sans-serif' },
  { family: 'Noto Sans', category: 'sans-serif' },
  { family: 'Lato', category: 'sans-serif' },
  { family: 'Montserrat', category: 'sans-serif' },
  { family: 'Poppins', category: 'sans-serif' },
  { family: 'Inter', category: 'sans-serif' },
  { family: 'Roboto Condensed', category: 'sans-serif' },
  { family: 'Oswald', category: 'sans-serif' },
  { family: 'Raleway', category: 'sans-serif' },
  { family: 'Nunito', category: 'sans-serif' },
  { family: 'Nunito Sans', category: 'sans-serif' },
  { family: 'Ubuntu', category: 'sans-serif' },
  { family: 'Rubik', category: 'sans-serif' },
  { family: 'Work Sans', category: 'sans-serif' },
  { family: 'Kanit', category: 'sans-serif' },
  { family: 'Fira Sans', category: 'sans-serif' },
  { family: 'Quicksand', category: 'sans-serif' },
  { family: 'Mulish', category: 'sans-serif' },
  { family: 'Barlow', category: 'sans-serif' },
  { family: 'Manrope', category: 'sans-serif' },
  { family: 'DM Sans', category: 'sans-serif' },
  { family: 'IBM Plex Sans', category: 'sans-serif' },
  { family: 'Karla', category: 'sans-serif' },
  { family: 'Cabin', category: 'sans-serif' },
  { family: 'Libre Franklin', category: 'sans-serif' },
  { family: 'Outfit', category: 'sans-serif' },
  { family: 'Exo 2', category: 'sans-serif' },
  { family: 'Assistant', category: 'sans-serif' },
  { family: 'Overpass', category: 'sans-serif' },
  { family: 'Lexend', category: 'sans-serif' },
  { family: 'Red Hat Display', category: 'sans-serif' },
  { family: 'Space Grotesk', category: 'sans-serif' },
  { family: 'Archivo', category: 'sans-serif' },
  { family: 'Signika', category: 'sans-serif' },
  { family: 'Catamaran', category: 'sans-serif' },
  { family: 'Figtree', category: 'sans-serif' },
  { family: 'Titillium Web', category: 'sans-serif' },
  { family: 'PT Sans', category: 'sans-serif' },
  { family: 'Mukta', category: 'sans-serif' },
  { family: 'Source Sans 3', category: 'sans-serif' },
  { family: 'Hind', category: 'sans-serif' },
  { family: 'Josefin Sans', category: 'sans-serif' },
  { family: 'Noto Sans JP', category: 'sans-serif' },
  { family: 'Arimo', category: 'sans-serif' },
  { family: 'Dosis', category: 'sans-serif' },
  { family: 'Varela Round', category: 'sans-serif' },
  { family: 'Maven Pro', category: 'sans-serif' },
  { family: 'Jost', category: 'sans-serif' },
  { family: 'Sora', category: 'sans-serif' },

  // Serif (~20)
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Playfair Display', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'PT Serif', category: 'serif' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Crimson Text', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Source Serif 4', category: 'serif' },
  { family: 'DM Serif Display', category: 'serif' },
  { family: 'Cormorant Garamond', category: 'serif' },
  { family: 'Zilla Slab', category: 'serif' },
  { family: 'IBM Plex Serif', category: 'serif' },
  { family: 'Spectral', category: 'serif' },
  { family: 'Vollkorn', category: 'serif' },
  { family: 'Arvo', category: 'serif' },
  { family: 'Frank Ruhl Libre', category: 'serif' },
  { family: 'Cardo', category: 'serif' },

  // Display (~15)
  { family: 'Bebas Neue', category: 'display' },
  { family: 'Anton', category: 'display' },
  { family: 'Lobster', category: 'display' },
  { family: 'Abril Fatface', category: 'display' },
  { family: 'Alfa Slab One', category: 'display' },
  { family: 'Righteous', category: 'display' },
  { family: 'Patua One', category: 'display' },
  { family: 'Fredoka', category: 'display' },
  { family: 'Lilita One', category: 'display' },
  { family: 'Bungee', category: 'display' },
  { family: 'Passion One', category: 'display' },
  { family: 'Fugaz One', category: 'display' },
  { family: 'Russo One', category: 'display' },
  { family: 'Secular One', category: 'display' },
  { family: 'Staatliches', category: 'display' },

  // Handwriting (~10)
  { family: 'Dancing Script', category: 'handwriting' },
  { family: 'Caveat', category: 'handwriting' },
  { family: 'Indie Flower', category: 'handwriting' },
  { family: 'Pacifico', category: 'handwriting' },
  { family: 'Shadows Into Light', category: 'handwriting' },
  { family: 'Satisfy', category: 'handwriting' },
  { family: 'Great Vibes', category: 'handwriting' },
  { family: 'Kalam', category: 'handwriting' },
  { family: 'Patrick Hand', category: 'handwriting' },
  { family: 'Architects Daughter', category: 'handwriting' },

  // Monospace (~13)
  { family: 'Roboto Mono', category: 'monospace' },
  { family: 'Source Code Pro', category: 'monospace' },
  { family: 'Fira Code', category: 'monospace' },
  { family: 'JetBrains Mono', category: 'monospace' },
  { family: 'IBM Plex Mono', category: 'monospace' },
  { family: 'Space Mono', category: 'monospace' },
  { family: 'Ubuntu Mono', category: 'monospace' },
  { family: 'Inconsolata', category: 'monospace' },
  { family: 'Cousine', category: 'monospace' },
  { family: 'Anonymous Pro', category: 'monospace' },
  { family: 'Overpass Mono', category: 'monospace' },
  { family: 'DM Mono', category: 'monospace' },
  { family: 'Red Hat Mono', category: 'monospace' },
]
